"""
Synthetic FIR (First Information Report) generator for the Maharashtra Crime Intelligence
& Analytics Platform (MAHACRIME-INTEL) demo.

DEMO / SYNTHETIC DATA NOTICE:
All incidents, suspects, victims, and specific FIR records generated by this script
are completely SYNTHETIC and generated for demonstration and analytical testing purposes only.
Real geographic coordinates of Maharashtra administrative districts and police stations
are used for realistic geospatial visualization, but incident rates and records do NOT
represent official Maharashtra Police crime statistics.

Injected ground-truth patterns (for ML validation & anomaly recovery):
1. Base daily rates per crime type
2. Weekend multiplier (Assault, Chain Snatching, Theft)
3. Night-hour multiplier (22:00-04:00) (Burglary, Vehicle Theft, Robbery)
4. Seasonal festival spike (Oct-Nov)
5. Hotspot station: Hinjawadi PS (Vehicle Theft x2.5)
6. Recent spike station: Shivajinagar PS (Robbery x5.0, last 4 weeks)
7. Repeat-offender MO ring: 5 suspects sharing MO across incidents and stations
"""

import os
import random
from datetime import datetime, timedelta
import numpy as np
from faker import Faker
import psycopg2
from psycopg2.extras import execute_values

fake = Faker("en_IN")
random.seed(42)
np.random.seed(42)

db_password = os.environ.get("DB_PASSWORD")
if not db_password:
    raise RuntimeError("DB_PASSWORD environment variable is required")

DB_CONFIG = dict(
    dbname=os.environ.get("DB_NAME", "ksp_crime"),
    user=os.environ.get("DB_USER", "postgres"),
    password=db_password,
    host=os.environ.get("DB_HOST", "localhost"),
    port=int(os.environ.get("DB_PORT", "5432")),
)

CRIME_TYPES = [
    "Theft",
    "Burglary",
    "Vehicle Theft",
    "Assault",
    "Robbery",
    "Cybercrime",
    "Chain Snatching",
]
WEAPONS = ["None", "Knife", "Blunt Object", "Firearm", "Improvised"]
TARGET_TYPES = ["Residence", "Commercial", "Vehicle", "Individual", "Public Space"]
ESCAPE_PATTERNS = ["On Foot", "Two-Wheeler", "Car", "Public Transport", "Unknown"]

# Comprehensive 36 Official Maharashtra Districts & Representative Police Stations with real coordinates
DISTRICTS = {
    "Mumbai City": [
        ("Colaba PS", 18.9154, 72.8258),
        ("Azad Maidan PS", 18.9405, 72.8335),
        ("Marine Drive PS", 18.9438, 72.8232),
        ("Dadar PS", 19.0201, 72.8436),
    ],
    "Mumbai Suburban": [
        ("Bandra PS", 19.0596, 72.8295),
        ("Andheri PS", 19.1136, 72.8697),
        ("Borivali PS", 19.2288, 72.8541),
        ("Kurla PS", 19.0726, 72.8845),
    ],
    "Pune": [
        ("Shivajinagar PS", 18.5314, 73.8446),
        ("Kothrud PS", 18.5074, 73.8077),
        ("Hinjawadi PS", 18.5913, 73.7389),
        ("Hadapsar PS", 18.5089, 73.9260),
    ],
    "Nagpur": [
        ("Sitabuldi PS", 21.1458, 79.0882),
        ("Sadar PS", 21.1610, 79.0820),
        ("Ambazari PS", 21.1290, 79.0490),
    ],
    "Thane": [
        ("Thane Nagar PS", 19.1944, 72.9733),
        ("Naupada PS", 19.1865, 72.9698),
        ("Wagle Estate PS", 19.1982, 72.9463),
    ],
    "Nashik": [
        ("Panchavati PS", 20.0063, 73.7997),
        ("Sarkarwada PS", 19.9975, 73.7898),
        ("Nashik Road PS", 19.9538, 73.8340),
    ],
    "Chhatrapati Sambhajinagar": [
        ("Kranti Chowk PS", 19.8762, 75.3240),
        ("Cidco PS", 19.8830, 75.3670),
        ("Begumpura PS", 19.9015, 75.3180),
    ],
    "Ahilyanagar": [
        ("Kotwali PS Ahilyanagar", 19.0952, 74.7496),
        ("Tophkhana PS", 19.0980, 74.7390),
        ("Shirdi PS", 19.7667, 74.4764),
    ],
    "Kolhapur": [
        ("Juna Rajwada PS", 16.6956, 74.2234),
        ("Shahupuri PS", 16.7050, 74.2433),
    ],
    "Solapur": [
        ("Sadar Bazar PS Solapur", 17.6698, 75.9064),
        ("Faujdar Chawadi PS", 17.6599, 75.9064),
    ],
    "Amravati": [
        ("Kotwali PS Amravati", 20.9320, 77.7523),
        ("Rajapeth PS", 20.9180, 77.7590),
    ],
    "Nanded": [
        ("Vazirabad PS", 19.1550, 77.3150),
        ("Bhagyanagar PS", 19.1620, 77.3080),
    ],
    "Jalgaon": [
        ("Jalgaon City PS", 21.0077, 75.5626),
        ("Bhusawal PS", 21.0455, 75.7885),
    ],
    "Akola": [
        ("Kotwali PS Akola", 20.7002, 77.0082),
        ("Civil Lines PS Akola", 20.7090, 77.0140),
    ],
    "Latur": [
        ("Gandhi Chowk PS", 18.4088, 76.5604),
        ("Shivaji Nagar PS Latur", 18.4020, 76.5810),
    ],
    "Dhule": [
        ("Dhule City PS", 20.9042, 74.7749),
        ("Azadnagar PS Dhule", 20.9001, 74.7812),
    ],
    "Satara": [
        ("Satara City PS", 17.6805, 74.0183),
        ("Karad PS", 17.2863, 74.1834),
    ],
    "Sangli": [
        ("Sangli City PS", 16.8524, 74.5815),
        ("Miraj PS", 16.8273, 74.6468),
    ],
    "Raigad": [
        ("Alibag PS", 18.6414, 72.8722),
        ("Panvel PS", 18.9894, 73.1175),
    ],
    "Ratnagiri": [
        ("Ratnagiri City PS", 16.9902, 73.3120),
        ("Chiplun PS", 17.5323, 73.5186),
    ],
    "Sindhudurg": [
        ("Sawantwadi PS", 15.9064, 73.8203),
        ("Kankavli PS", 16.2690, 73.7056),
    ],
    "Palghar": [
        ("Palghar PS", 19.6967, 72.7655),
        ("Vasai PS", 19.3919, 72.8397),
    ],
    "Nandurbar": [
        ("Nandurbar City PS", 21.3700, 74.2400),
        ("Shahada PS", 21.5430, 74.4710),
    ],
    "Jalna": [
        ("Kadim Jalna PS", 19.8410, 75.8860),
        ("Sadar Bazar PS Jalna", 19.8340, 75.8820),
    ],
    "Beed": [
        ("Shivaji Nagar PS Beed", 18.9891, 75.7601),
        ("Beed City PS", 18.9950, 75.7520),
    ],
    "Dharashiv": [
        ("Anand Nagar PS", 18.1856, 76.0419),
        ("Dharashiv City PS", 18.1780, 76.0380),
    ],
    "Parbhani": [
        ("Kotwali PS Parbhani", 19.2610, 76.7740),
        ("Naya Mondha PS", 19.2720, 76.7820),
    ],
    "Hingoli": [
        ("Hingoli City PS", 19.7180, 77.1480),
        ("Hingoli Rural PS", 19.7250, 77.1600),
    ],
    "Buldhana": [
        ("Buldhana City PS", 20.5290, 76.1840),
        ("Khamgaon PS", 20.6860, 76.5710),
    ],
    "Washim": [
        ("Washim City PS", 20.1110, 77.1350),
        ("Risod PS", 19.9670, 76.7830),
    ],
    "Wardha": [
        ("Wardha City PS", 20.7453, 78.5974),
        ("Sewagram PS", 20.7120, 78.6110),
    ],
    "Yavatmal": [
        ("Yavatmal City PS", 20.3888, 78.1204),
        ("Wadgaon PS", 20.3990, 78.1340),
    ],
    "Bhandara": [
        ("Bhandara City PS", 21.1710, 79.6540),
        ("Tumsar PS", 21.3810, 79.7420),
    ],
    "Gondia": [
        ("Gondia City PS", 21.4598, 80.1961),
        ("Ramnagar PS Gondia", 21.4680, 80.2050),
    ],
    "Chandrapur": [
        ("Chandrapur City PS", 19.9615, 79.2961),
        ("Ramnagar PS Chandrapur", 19.9720, 79.3080),
    ],
    "Gadchiroli": [
        ("Gadchiroli City PS", 20.1809, 80.0028),
        ("Kurkheda PS", 20.6020, 80.1740),
    ],
}

SIM_START = datetime(2024, 1, 1)
SIM_END = datetime(2025, 12, 31)
TOTAL_DAYS = (SIM_END - SIM_START).days

# --- Deliberately injected patterns (log these; model recovers them) ---
# 1. Base daily rate per (station, crime_type) — some crime types are rarer.
BASE_RATE = {
    "Theft": 0.35,
    "Burglary": 0.20,
    "Vehicle Theft": 0.25,
    "Assault": 0.18,
    "Robbery": 0.10,
    "Cybercrime": 0.15,
    "Chain Snatching": 0.12,
}
# 2. Weekend multiplier — certain crimes spike on weekends
WEEKEND_MULTIPLIER = {"Assault": 1.8, "Chain Snatching": 1.6, "Theft": 1.3}
# 3. Night-hour multiplier (10pm-4am) — burglary/vehicle theft skew heavily to night
NIGHT_MULTIPLIER = {"Burglary": 2.2, "Vehicle Theft": 1.9, "Robbery": 1.5}
# 4. Seasonal spike — festival season (Oct-Nov) sees a Chain Snatching / Theft spike
SEASONAL_MONTHS = {10, 11}
SEASONAL_MULTIPLIER = {"Chain Snatching": 2.0, "Theft": 1.4}
# 5. One station is deliberately made a "hotspot" for Vehicle Theft to test hotspot detection
HOTSPOT_STATION = "Hinjawadi PS"
HOTSPOT_CRIME = "Vehicle Theft"
HOTSPOT_MULTIPLIER = 2.5
# 6. A DIFFERENT station gets a sudden RECENT spike (last 4 weeks only) in a different crime type
RECENT_SPIKE_STATION = "Shivajinagar PS"
RECENT_SPIKE_CRIME = "Robbery"
RECENT_SPIKE_MULTIPLIER = 5.0
RECENT_SPIKE_WEEKS = 4


def daily_rate(crime_type, day, station_name):
    rate = BASE_RATE[crime_type]
    is_weekend = day.weekday() >= 5
    if is_weekend:
        rate *= WEEKEND_MULTIPLIER.get(crime_type, 1.0)
    if day.month in SEASONAL_MONTHS:
        rate *= SEASONAL_MULTIPLIER.get(crime_type, 1.0)
    if station_name == HOTSPOT_STATION and crime_type == HOTSPOT_CRIME:
        rate *= HOTSPOT_MULTIPLIER
    if (
        station_name == RECENT_SPIKE_STATION
        and crime_type == RECENT_SPIKE_CRIME
        and day >= SIM_END - timedelta(weeks=RECENT_SPIKE_WEEKS)
    ):
        rate *= RECENT_SPIKE_MULTIPLIER
    return rate


def _night_probability_for_ratio(target_ratio, night_hours=7, day_hours=17):
    return (target_ratio * night_hours) / (day_hours + target_ratio * night_hours)


_NIGHT_PROBABILITY = {
    ct: _night_probability_for_ratio(mult) for ct, mult in NIGHT_MULTIPLIER.items()
}


def random_hour(crime_type):
    if (
        crime_type in _NIGHT_PROBABILITY
        and random.random() < _NIGHT_PROBABILITY[crime_type]
    ):
        return random.choice(list(range(22, 24)) + list(range(0, 5)))
    return random.randint(5, 21)


def jitter(lat, long, meters=1200):
    deg = meters / 111_000
    return lat + random.uniform(-deg, deg), long + random.uniform(-deg, deg)


def main():
    conn = psycopg2.connect(**DB_CONFIG)
    cur = conn.cursor()

    print("Resetting database schema tables...")
    schema_sql_path = os.path.join(os.path.dirname(__file__), "schema.sql")
    if os.path.exists(schema_sql_path):
        with open(schema_sql_path, "r") as sf:
            cur.execute(sf.read())
        conn.commit()
    else:
        cur.execute("TRUNCATE incident_suspects, incident_victims, incidents, suspects, victims, stations RESTART IDENTITY CASCADE;")
        conn.commit()

    # --- Insert stations across all 36 Maharashtra districts ---
    station_ids = {}
    print(f"Inserting stations for {len(DISTRICTS)} Maharashtra districts...")
    for district, stations in DISTRICTS.items():
        for name, lat, long in stations:
            cur.execute(
                """INSERT INTO stations (name, district, lat, long, jurisdiction_polygon)
                   VALUES (%s, %s, %s, %s,
                       ST_SetSRID(ST_Buffer(ST_MakePoint(%s, %s)::geography, 3000)::geometry, 4326))
                   RETURNING id""",
                (name, district, lat, long, long, lat),
            )
            station_ids[name] = cur.fetchone()[0]
    conn.commit()

    # --- Insert suspects and victims ---
    N_SUSPECTS = 250
    N_VICTIMS = 500
    print(f"Inserting {N_SUSPECTS} suspects and {N_VICTIMS} victims...")
    suspect_ids = []
    for _ in range(N_SUSPECTS):
        cur.execute("INSERT INTO suspects (name) VALUES (%s) RETURNING id", (fake.name(),))
        suspect_ids.append(cur.fetchone()[0])
    victim_ids = []
    for _ in range(N_VICTIMS):
        cur.execute("INSERT INTO victims (name) VALUES (%s) RETURNING id", (fake.name(),))
        victim_ids.append(cur.fetchone()[0])
    conn.commit()

    # --- Deliberately inject a repeat-offender ring (5 suspects sharing MO) ---
    ring_suspects = suspect_ids[:5]
    RING_MO = dict(weapon_or_method="Improvised", target_type="Commercial", escape_pattern="Two-Wheeler")

    # --- Generate incidents ---
    print("Generating synthetic incidents across timeline...")
    incidents_created = 0
    incident_rows = []
    for district, stations in DISTRICTS.items():
        for name, lat, long in stations:
            sid = station_ids[name]
            for day_offset in range(TOTAL_DAYS):
                day = SIM_START + timedelta(days=day_offset)
                for crime_type in CRIME_TYPES:
                    rate = daily_rate(crime_type, day, name)
                    count = np.random.poisson(rate)
                    for _ in range(count):
                        hour = random_hour(crime_type)
                        ts = day + timedelta(hours=hour, minutes=random.randint(0, 59))
                        ilat, ilong = jitter(lat, long)
                        weapon = random.choice(WEAPONS)
                        target = random.choice(TARGET_TYPES)
                        escape = random.choice(ESCAPE_PATTERNS)
                        incident_rows.append((sid, ilat, ilong, crime_type, ts, weapon, target, escape))
                        incidents_created += 1

    print(f"Inserting {incidents_created} synthetic incidents into PostgreSQL...")
    execute_values(
        cur,
        """INSERT INTO incidents (station_id, lat, long, crime_type, "timestamp",
               weapon_or_method, target_type, escape_pattern)
           VALUES %s RETURNING id""",
        incident_rows,
        fetch=False,
    )
    conn.commit()

    # Fetch back incident ids to link suspects/victims
    cur.execute("SELECT id, crime_type FROM incidents ORDER BY id")
    all_incidents = cur.fetchall()

    print("Linking suspects and victims to incidents...")
    ring_incident_count = 0
    link_rows_s, link_rows_v = [], []
    ring_incident_ids = []
    for inc_id, crime_type in all_incidents:
        # 8% chance this incident belongs to the deliberately injected ring
        if crime_type in ("Vehicle Theft", "Theft") and random.random() < 0.08:
            sus = random.choice(ring_suspects)
            ring_incident_count += 1
            ring_incident_ids.append(inc_id)
        else:
            sus = random.choice(suspect_ids)
        link_rows_s.append((inc_id, sus))
        n_victims = random.randint(1, 2)
        for v in random.sample(victim_ids, n_victims):
            link_rows_v.append((inc_id, v))

    execute_values(cur, "INSERT INTO incident_suspects (incident_id, suspect_id) VALUES %s", link_rows_s)
    execute_values(cur, "INSERT INTO incident_victims (incident_id, victim_id) VALUES %s", link_rows_v)

    if ring_incident_ids:
        cur.execute(
            """UPDATE incidents SET weapon_or_method = %s, target_type = %s, escape_pattern = %s
               WHERE id = ANY(%s)""",
            (RING_MO["weapon_or_method"], RING_MO["target_type"], RING_MO["escape_pattern"], ring_incident_ids),
        )
    conn.commit()

    cur.close()
    conn.close()

    print("=" * 70)
    print("MAHARASHTRA SYNTHETIC DATA GENERATION SUMMARY (DEMO DATA)")
    print("=" * 70)
    print(f"Total incidents created: {incidents_created}")
    print(f"Date range: {SIM_START.date()} to {SIM_END.date()}")
    print(f"Stations: {sum(len(v) for v in DISTRICTS.values())} across {len(DISTRICTS)} Maharashtra districts")
    print(f"Suspects: {N_SUSPECTS} | Victims: {N_VICTIMS}")
    print("\nInjected ground-truth patterns:")
    print(f"1. Base rates: {BASE_RATE}")
    print(f"2. Weekend multipliers: {WEEKEND_MULTIPLIER}")
    print(f"3. Night-hour multipliers (22:00-04:00): {NIGHT_MULTIPLIER}")
    print(f"4. Seasonal spike (Oct-Nov): {SEASONAL_MULTIPLIER}")
    print(f"5. Hotspot station: '{HOTSPOT_STATION}' ({HOTSPOT_CRIME} x{HOTSPOT_MULTIPLIER})")
    print(f"6. Recent spike: '{RECENT_SPIKE_STATION}' ({RECENT_SPIKE_CRIME} x{RECENT_SPIKE_MULTIPLIER}, last {RECENT_SPIKE_WEEKS} wks)")
    print(f"7. MO ring: 5 suspects (ids {ring_suspects}) across {ring_incident_count} incidents")
    print("=" * 70)


if __name__ == "__main__":
    main()